### ISSUE TITLE
The .spec.transport.noise field is required even though all fields in Noise transport are optional

### ISSUE THREAD

**Issue by crmin** [crmin/rathole-operator#2]
Even though all child properties of transport.noise are optional, k8s resource requires the .spec.transport.noise property even for empty objects.

For example, in the case below, an error occurs with a message that the .spec.transport.noise field is required.

```yaml
apiVersion: rathole.superclass.io/v1alpha1
kind: RatholeServer
metadata:
  name: rathole-server-1
  namespace: default
spec:
  configTarget:
    resourceType: configmap
    name: rathole-server-1
  bindAddr: 0.0.0.0:8000
  transport:
    type: noise
```

In the case below, it is created without a problem.

```yaml
apiVersion: rathole.superclass.io/v1alpha1
kind: RatholeServer
metadata:
  name: rathole-server-1
  namespace: default
spec:
  configTarget:
    resourceType: configmap
    name: rathole-server-1
  bindAddr: 0.0.0.0:8000
  transport:
    type: noise
    noise: {}
```
